info:
  app:
    name: music
    version: 1.0.1
server:
  port:
  address:
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  mvc:
    date-format: yyyy-MM-dd
    throw-exception-if-no-handler-found: true # 找不到处理器直接抛出异常
  resources:
    add-mappings: false # 不要为我们工程中的资源文件建立映射
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.172.123:3306/k12?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: true
